/**
 * Ranch Hand IO API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AddressWriteDTO { 
    /**
     * Street address 1 of address
     */
    street_address1: string;
    street_address2?: string | null;
    /**
     * City of address
     */
    city: string;
    /**
     * State of address
     */
    state: string;
    /**
     * Postal_code of address
     */
    postal_code: string;
    /**
     * Country of address
     */
    country?: string;
}

