/**
 * Ranch Hand IO API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AddressResponseDTO { 
    /**
     * Street address 1 of address
     */
    street_address1: string;
    street_address2?: string | null;
    /**
     * City of address
     */
    city: string;
    /**
     * State of address
     */
    state: string;
    /**
     * Postal_code of address
     */
    postal_code: string;
    /**
     * Country of address
     */
    country?: string;
    /**
     * Primary key of the record
     */
    id: string;
    /**
     * Indicates if the record is active
     */
    is_active?: boolean;
    /**
     * Who created the record
     */
    created_by?: string;
    /**
     * Creation timestamp of the record
     */
    created_at: string;
    updated_by?: string | null;
    updated_at?: string | null;
}

