/**
 * Ranch Hand IO API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubscriptionResponseDTO } from './subscriptionResponseDTO';


export interface ApiResponseDTOListSubscriptionResponseDTO { 
    status_code?: number;
    message?: string;
    success?: boolean;
    data: Array<SubscriptionResponseDTO>;
    error?: string;
    count?: number;
}

