/**
 * Ranch Hand IO API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScopeResponseDTO } from './scopeResponseDTO';


export interface ApiResponseDTOListScopeResponseDTO { 
    status_code?: number;
    message?: string;
    success?: boolean;
    data: Array<ScopeResponseDTO>;
    error?: string;
    count?: number;
}

