/**
 * Ranch Hand IO API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserResponseDTO } from './userResponseDTO';


export interface ApiResponseDTOUserResponseDTO { 
    status_code?: number;
    message?: string;
    success?: boolean;
    data: UserResponseDTO;
    error?: string;
    count?: number;
}

