/**
 * Ranch Hand IO API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const BillingCycle = {
    Weekly: 'weekly',
    BiWeekly: 'bi-weekly',
    Monthly: 'monthly',
    Quarterly: 'quarterly',
    SemiAnnually: 'semi-annually',
    Annually: 'annually'
} as const;
export type BillingCycle = typeof BillingCycle[keyof typeof BillingCycle];

