/**
 * Ranch Hand IO API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressResponseDTO } from './addressResponseDTO';


export interface PeopleResponseDTO { 
    /**
     * First name of person
     */
    first_name: string;
    /**
     * Last name of person
     */
    last_name: string;
    /**
     * Email address of person
     */
    email: string;
    phone_number1?: string | null;
    phone_number2?: string | null;
    primary_address_id?: string | null;
    primary_address?: AddressResponseDTO | null;
    secondary_address_id?: string | null;
    secondary_address?: AddressResponseDTO | null;
    date_of_birth?: string | null;
    /**
     * Primary key of the record
     */
    id: string;
    /**
     * Indicates if the record is active
     */
    is_active?: boolean;
    /**
     * Who created the record
     */
    created_by?: string;
    /**
     * Creation timestamp of the record
     */
    created_at: string;
    updated_by?: string | null;
    updated_at?: string | null;
}

