/**
 * Ranch Hand IO API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressWriteDTO } from './addressWriteDTO';


export interface PeopleWriteDTO { 
    /**
     * First name of person
     */
    first_name: string;
    /**
     * Last name of person
     */
    last_name: string;
    /**
     * Email address of person
     */
    email: string;
    phone_number1?: string | null;
    phone_number2?: string | null;
    primary_address_id?: string | null;
    primary_address?: AddressWriteDTO | null;
    secondary_address_id?: string | null;
    secondary_address?: AddressWriteDTO | null;
    date_of_birth?: string | null;
}

