/**
 * Ranch Hand IO API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScopeResponseDTO } from './scopeResponseDTO';


export interface RoleResponseDTO { 
    /**
     * Name of the role
     */
    name: string;
    /**
     * Code of the role
     */
    code: string;
    description?: string | null;
    /**
     * Primary key of the record
     */
    id: string;
    /**
     * Indicates if the record is active
     */
    is_active?: boolean;
    /**
     * Who created the record
     */
    created_by?: string;
    /**
     * Creation timestamp of the record
     */
    created_at: string;
    updated_by?: string | null;
    updated_at?: string | null;
    /**
     * List of scopes associated with the role
     */
    scopes?: Array<ScopeResponseDTO>;
}

