/**
 * Ranch Hand IO API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BillingCycle } from './billingCycle';
import { ScopeResponseDTO } from './scopeResponseDTO';


export interface SubscriptionResponseDTO { 
    /**
     * Name of subscription
     */
    name: string;
    /**
     * Description of subscription
     */
    description: string;
    /**
     * Max user count allowed in subscription
     */
    max_users: number;
    /**
     * Price of subscription
     */
    price: number;
    /**
     * Billing cycle for subscription
     */
    billing_cycle: BillingCycle;
    /**
     * Primary key of the record
     */
    id: string;
    /**
     * Indicates if the record is active
     */
    is_active?: boolean;
    /**
     * Who created the record
     */
    created_by?: string;
    /**
     * Creation timestamp of the record
     */
    created_at: string;
    updated_by?: string | null;
    updated_at?: string | null;
    scopes?: Array<ScopeResponseDTO> | null;
}
export namespace SubscriptionResponseDTO {
}


