/**
 * Ranch Hand IO API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BillingCycle } from './billingCycle';


export interface SubscriptionWriteDTO { 
    /**
     * Name of subscription
     */
    name: string;
    /**
     * Description of subscription
     */
    description: string;
    /**
     * Max user count allowed in subscription
     */
    max_users: number;
    /**
     * Price of subscription
     */
    price: number;
    /**
     * Billing cycle for subscription
     */
    billing_cycle: BillingCycle;
}
export namespace SubscriptionWriteDTO {
}


