/**
 * Ranch Hand IO API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TenantWriteDTO { 
    /**
     * Name of the tenant
     */
    name: string;
    /**
     * Code of the tenant
     */
    slug: string;
    description?: string | null;
}

