/**
 * Ranch Hand IO API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserWriteDTO { 
    /**
     * Unique identifier for the person associated with the user
     */
    person_id: string;
    /**
     * Username of the user
     */
    username: string;
    /**
     * Email address of the user
     */
    email: string;
    /**
     * Password for the user
     */
    password: string;
    /**
     * Indicates if multi-factor authentication is enabled for the user
     */
    mfa_enabled?: boolean;
    otp_code?: string | null;
}

