/**
 * Ranch Hand IO API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleResponseDTO } from './roleResponseDTO';
import { TenantResponseDTO } from './tenantResponseDTO';
import { ScopeResponseDTO } from './scopeResponseDTO';
import { PeopleResponseDTO } from './peopleResponseDTO';


export interface UserResponseDTO { 
    /**
     * Unique identifier for the person associated with the user
     */
    person_id: string;
    /**
     * Username of the user
     */
    username: string;
    /**
     * Email address of the user
     */
    email: string;
    /**
     * Hidden password
     */
    password?: string;
    /**
     * Indicates if multi-factor authentication is enabled for the user
     */
    mfa_enabled?: boolean;
    otp_code?: string | null;
    /**
     * Primary key of the record
     */
    id: string;
    /**
     * Indicates if the record is active
     */
    is_active?: boolean;
    /**
     * Who created the record
     */
    created_by?: string;
    /**
     * Creation timestamp of the record
     */
    created_at: string;
    updated_by?: string | null;
    updated_at?: string | null;
    /**
     * Person record tied to user
     */
    person: PeopleResponseDTO;
    tenants?: Array<TenantResponseDTO> | null;
    roles?: Array<RoleResponseDTO> | null;
    scopes?: Array<ScopeResponseDTO> | null;
}

