export * from './addresses.service';
import { AddressesService } from './addresses.service';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './healthCheck.service';
import { HealthCheckService } from './healthCheck.service';
export * from './people.service';
import { PeopleService } from './people.service';
export * from './roles.service';
import { RolesService } from './roles.service';
export * from './scopes.service';
import { ScopesService } from './scopes.service';
export * from './subscriptions.service';
import { SubscriptionsService } from './subscriptions.service';
export * from './tenants.service';
import { TenantsService } from './tenants.service';
export * from './users.service';
import { UsersService } from './users.service';
export const APIS = [AddressesService, AuthService, HealthCheckService, PeopleService, RolesService, ScopesService, SubscriptionsService, TenantsService, UsersService];
